### PR TITLE
bump version to v1.3.0, update deps

### PR DESCRIPTION
**Pull request by jhossbach**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jhossbach** [comment]
@conda-forge-admin, please rerender

**Comment by jhossbach** [comment]
I am a bit confused; There seem to have been two merges to the staged-recipes repo both by you and me? https://github.com/conda-forge/staged-recipes/pull/22139 and https://github.com/conda-forge/staged-recipes/pull/22294

Anyways, how would you feel about joined maintaining (if possible) as I am also maintaining the `python-lsp-ruff` package?

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
> been two merges to the staged-recipes repo both by you and me?

Yeah, that's strange: not sure why the later one "won,"

> maintaining

of course! more people to press buttons is always good, _especially_ upstream maintainers! 

we'll get this one through, and it should be sorted.

**Review by bollwyvl — APPROVED** [review]

**Pull request merged**
