### PR TITLE
Use python-lsp-server-base package

### LINKED ISSUE #3: Depend on python-lsp-server-base instead of python-lsp-server, as it differs from pypi
### Comment:

The conda-forge package "python-lsp-server" is equivalent to "python-lsp-server[all]" on PyPI. Which installs dependencies like pylint, pydocstyle, etc.. which all can be replaced by ruff.

The PyPI package "python-lsp-ruff" only dependends on the "python-lsp-server" PyPI package which would be "python-lsp-server-base" on conda-forge. 

The conda-forge package "python-lsp-server" depends on "python-lsp-server-base", so it shouldn't break existing installations and if people want the current behaviour they simply can install the "python-lsp-server" conda-forge package and there will be no dependency problems.

Would be great if this could be changed, as this differs from the pypi package.

Thanks!

### PR DESCRIPTION
**Pull request by jonas-w**
Fixes #3

Tested it locally and it worked just by changing to the base package.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonas-w** [comment]
@conda-forge-admin, please rerender

**Review by bollwyvl — APPROVED** [review]

**Comment by bollwyvl** [comment]
Thanks for looking out for this! The upstream is a bit of a mess, due to the long and complex history of this functionality, and anything that makes it simpler to get up and running is great.

**Comment by jonas-w** [comment]
Thanks for merging it that quickly!

**Comment by bollwyvl** [comment]
Yep... Tests with coverage make review easy!

**Pull request merged**
